require:
  - rubocop-capybara
  - rubocop-rails
  - rubocop-rspec
  - rubocop-factory_bot

AllCops:
  NewCops: enable

Style/Documentation:
  Enabled: false

Layout/LineLength:
  Exclude:
    - 'config/initializers/devise.rb'
    - 'spec/**/*.rb'

Rails/LexicallyScopedActionFilter:
  Exclude:
    - 'app/controllers/users/registrations_controller.rb'

RSpec/ExampleLength:
  Max: 10

RSpec/MultipleExpectations:
  Max: 10