# fly.toml app configuration file generated for daily-dish on 2023-09-22T21:10:57+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "daily-dish"
primary_region = "ams"
console_command = "/rails/bin/rails console"

[build]

[mounts]
  source="daily_dish_sqlite"
  destination="/mnt/daily_dish_sqlite"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[[statics]]
  guest_path = "/rails/public"
  url_prefix = "/"
