# .github/workflows/rubocop.yml
name: Rubocop

on:
  pull_request:
  # push:
  #   branches:
  #     - 'main'

jobs:
  build:
    name: CI Rubocop
    runs-on: ubuntu-latest
    env:
      api-dir: ./

    steps:
      - uses: actions/checkout@v2
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.2.0
          bundler-cache: true
      - name: Check Rubocop Styles
        working-directory: ${{env.api-dir}}
        run: bundle exec rubocop